[package]
name = "habits"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["rt", "macros"] }
anyhow = "1.0.80"
futures = "0.3.30"
nom = "7.1.3"
clap = { version = "4.5.2", features = ["derive"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
